"""
Collect simulation data for the Monaco traffic dashboard.

For the base network and N randomly-degraded networks we run a SUMO simulation
with time-binned edge-level output (mean speed), then store:
  - per-edge road geometry (polyline shapes)
  - per-time-bin congestion ratio per edge (mean speed / speed limit, 0..1)
  - aggregate trip metrics (waiting/travel/time-loss/throughput ...)
  - which edges were removed / added vs. the base network

Everything is dumped to results/Monaco/dashboard/dashboard_data.pkl which the
Streamlit dashboard (dashboard.py) reads.
"""
import os
import copy
import pickle
import argparse
import subprocess
import xml.etree.ElementTree as ET

import random
import numpy as np
import networkx as nx

import traci
import sumolib
from sumolib.miscutils import getFreeSocketPort

from data_collection_monaco import get_default_network, construct_network_file

# gen networks are generated by removing edges from the dense network
DENSE_NET = "sumo/Monaco/default_dense.net.xml"
# the "original" network shown as the baseline in the dashboard
ORIGINAL_NET = "sumo/Monaco/default.net.xml"
# all simulations use the same route demand for a fair comparison
ROUTE_FILE = "sumo/Monaco/default_dense.rou.xml"

# kept for backward compatibility with helpers that reference BASE_NET
BASE_NET = DENSE_NET


def select_removed_edges(idx, possible_edges, masks, seed):
    """Replicates the edge-removal + connectivity-repair logic from
    data_collection_monaco.simulation(), returning the final remove list."""
    random.seed(seed + idx)
    np.random.seed(seed + idx)
    remove_ratio = np.random.uniform(0.05, 0.5)
    xs = np.random.choice(2, size=len(possible_edges), p=[1 - remove_ratio, remove_ratio])
    xs[masks == 1] = 0
    remove_edges = [possible_edges[i] for i in range(len(xs)) if xs[i] == 1]

    sumocfg_file = "sumo/Monaco/monaco.sumocfg"
    with open(sumocfg_file, "w") as f:
        f.write('<configuration>\n    <input>\n')
        f.write('        <net-file value="default_dense.net.xml"/>\n')
        f.write('        <route-files value="default_dense.rou.xml"/>\n')
        f.write('    </input>\n    <time>\n        <begin value="0"/>\n        <end value="3600"/>\n    </time>\n</configuration>\n')

    sumo_cmd = ["sumo", "-c", sumocfg_file, "--tripinfo-output", "sumo/Monaco/mocano.tripinfo.xml"]
    port = getFreeSocketPort()
    traci.start(sumo_cmd, port=port)
    node_list = traci.junction.getIDList()
    edge_list = traci.edge.getIDList()

    G = nx.Graph()
    for node in node_list:
        G.add_node(node, pos=(traci.junction.getPosition(node)))
    for edge in edge_list:
        G.add_edge(traci.edge.getFromJunction(edge), traci.edge.getToJunction(edge))

    G_new = copy.deepcopy(G)
    for edge in remove_edges:
        s, e = traci.edge.getFromJunction(edge), traci.edge.getToJunction(edge)
        if G_new.has_edge(s, e):
            G_new.remove_edge(s, e)

    for _ in range(10):
        add_edges = []
        for node in G_new.nodes():
            neighbors = list(G_new.neighbors(node))
            if len(neighbors) <= 1:
                cand = list(set(G.neighbors(node)) - set(G_new.neighbors(node)))
                cand = list(sorted(cand))
                if len(cand) > 0:
                    chosen = np.random.choice(cand)
                    add_edges.append((node, chosen))
                    for out_e in traci.junction.getOutgoingEdges(node):
                        if out_e in traci.junction.getIncomingEdges(chosen):
                            if out_e in remove_edges:
                                remove_edges.remove(out_e)
                            elif f"-{out_e}" in remove_edges:
                                remove_edges.remove(f"-{out_e}")
                            else:
                                continue
                            break
        for edge in add_edges:
            G_new.add_edge(edge[0], edge[1])

    remove_edges_pair = [edge[1:] for edge in remove_edges]
    remove_edges += remove_edges_pair
    traci.close()
    return xs, remove_edges


def run_sim_with_edgedata(net_file, sim_time, period, prefix):
    """Run SUMO on net_file, producing tripinfo + time-binned edge data.
    Returns (aggregate_metrics_dict, edge_timeseries, interval_begins)."""
    cfg = f"{prefix}.sumocfg"
    add_file = f"{prefix}.edgedata_add.xml"
    edgedata_out = os.path.abspath(f"{prefix}.edgedata.xml")
    tripinfo_out = os.path.abspath(f"{prefix}.tripinfo.xml")
    net_abs = os.path.abspath(net_file)
    route_abs = os.path.abspath(ROUTE_FILE)

    with open(cfg, "w") as f:
        f.write('<configuration>\n    <input>\n')
        f.write(f'        <net-file value="{net_abs}"/>\n')
        f.write(f'        <route-files value="{route_abs}"/>\n')
        f.write('    </input>\n    <time>\n        <begin value="0"/>\n')
        f.write(f'        <end value="{sim_time}"/>\n    </time>\n</configuration>\n')

    with open(add_file, "w") as f:
        f.write('<additional>\n')
        f.write(f'    <edgeData id="cong" file="{edgedata_out}" period="{period}" '
                f'begin="0" end="{sim_time}" excludeEmpty="false" minSamples="1"/>\n')
        f.write('</additional>\n')

    cmd = ["sumo", "-c", cfg, "--additional-files", os.path.abspath(add_file),
           "--tripinfo-output", tripinfo_out, "--no-warnings", "--no-step-log",
           "--seed", "42"]
    subprocess.run(cmd, check=True)

    # --- aggregate trip metrics ---
    waiting, duration, timeloss, route_len = [], [], [], []
    last_arrival = 0.0
    tree = ET.parse(tripinfo_out)
    for child in tree.getroot():
        waiting.append(float(child.attrib["waitingTime"]))
        duration.append(float(child.attrib["duration"]))
        timeloss.append(float(child.attrib.get("timeLoss", 0.0)))
        route_len.append(float(child.attrib.get("routeLength", 0.0)))
        last_arrival = max(last_arrival, float(child.attrib["arrival"]))
    metrics = {
        "num_arrived": len(duration),
        "avg_waiting_time": float(np.mean(waiting)) if waiting else float("nan"),
        "avg_travel_time": float(np.mean(duration)) if duration else float("nan"),
        "avg_time_loss": float(np.mean(timeloss)) if timeloss else float("nan"),
        "avg_route_length": float(np.mean(route_len)) if route_len else float("nan"),
        "last_arrival": last_arrival,
    }

    # --- per-edge speed limits (for congestion ratio) ---
    net = sumolib.net.readNet(net_file)
    speed_limit = {e.getID(): max(e.getSpeed(), 0.1) for e in net.getEdges()}

    # --- time-binned congestion ratio ---
    timeseries = []   # list over intervals; each is {edge_id: ratio in 0..1}
    begins = []
    etree = ET.parse(edgedata_out)
    for interval in etree.getroot().findall("interval"):
        begins.append(float(interval.attrib["begin"]))
        frame = {}
        for edge in interval.findall("edge"):
            eid = edge.attrib["id"]
            spd = edge.attrib.get("speed")
            if spd is None or eid not in speed_limit:
                continue
            ratio = float(spd) / speed_limit[eid]
            frame[eid] = float(min(max(ratio, 0.0), 1.0))
        timeseries.append(frame)

    return metrics, timeseries, begins


def edge_geometry(net_file):
    """Return {edge_id: {'shape': [[x,y],...], 'speed': limit}} and boundary."""
    net = sumolib.net.readNet(net_file)
    geom = {}
    for e in net.getEdges():
        geom[e.getID()] = {
            "shape": [[float(x), float(y)] for (x, y) in e.getShape()],
            "speed": float(e.getSpeed()),
        }
    return geom, list(net.getBoundary())


def avg_ratio_per_edge(timeseries):
    """Average congestion ratio over time for each edge."""
    acc, cnt = {}, {}
    for frame in timeseries:
        for eid, r in frame.items():
            acc[eid] = acc.get(eid, 0.0) + r
            cnt[eid] = cnt.get(eid, 0) + 1
    return {eid: acc[eid] / cnt[eid] for eid in acc}


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--num_networks", type=int, default=5)
    parser.add_argument("--simulation_time", type=int, default=1800)
    parser.add_argument("--period", type=int, default=60)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    out_dir = "results/Monaco/dashboard"
    os.makedirs(out_dir, exist_ok=True)
    work_dir = "sumo/Monaco/dashboard"
    os.makedirs(work_dir, exist_ok=True)

    random.seed(args.seed)
    np.random.seed(args.seed)

    # possible/eternal edges (uses cached eternal_edges.pkl); gens are removals
    # from the DENSE network, so generation logic still runs on default_dense.
    possible_edges, masks = get_default_network(DENSE_NET)

    # full-map bounds (from the dense superset) so every figure shares one view
    _, map_bounds = edge_geometry(DENSE_NET)
    data = {"networks": {}, "map_bounds": map_bounds}

    # ---- base ("original") network = default (sparse), same routes as gens ----
    print("[base] running simulation on ORIGINAL (default) network ...")
    base_geom, base_bounds = edge_geometry(ORIGINAL_NET)
    base_metrics, base_ts, base_begins = run_sim_with_edgedata(
        ORIGINAL_NET, args.simulation_time, args.period, f"{work_dir}/base")
    base_edge_ids = set(base_geom.keys())
    data["base"] = {
        "name": "base",
        "edges": base_geom,
        "bounds": base_bounds,
        "metrics": base_metrics,
        "timeseries": base_ts,
        "begins": base_begins,
        "avg_ratio": avg_ratio_per_edge(base_ts),
    }
    base_avg_ratio = data["base"]["avg_ratio"]
    print(f"  base: {base_metrics['num_arrived']} vehicles arrived, "
          f"avg wait {base_metrics['avg_waiting_time']:.1f}s")

    # ---- degraded networks ----
    for idx in range(args.num_networks):
        name = f"gen_{idx}"
        print(f"[{name}] selecting removed edges + running simulation ...")
        xs, remove_edges = select_removed_edges(idx, possible_edges, masks, args.seed)
        net_file = f"{work_dir}/{name}.net.xml"
        construct_network_file(net_file, remove_edges)

        geom, bounds = edge_geometry(net_file)
        metrics, ts, begins = run_sim_with_edgedata(
            net_file, args.simulation_time, args.period, f"{work_dir}/{name}")

        gen_edge_ids = set(geom.keys())
        removed = sorted(base_edge_ids - gen_edge_ids)
        added = sorted(gen_edge_ids - base_edge_ids)
        avg_ratio = avg_ratio_per_edge(ts)

        # traffic-flow change vs base on shared edges (positive = faster/better)
        flow_delta = {eid: avg_ratio.get(eid, np.nan) - base_avg_ratio.get(eid, np.nan)
                      for eid in (gen_edge_ids & base_edge_ids)}

        data["networks"][name] = {
            "name": name,
            "edges": geom,
            "bounds": bounds,
            "metrics": metrics,
            "timeseries": ts,
            "begins": begins,
            "avg_ratio": avg_ratio,
            "removed_edges": removed,
            "added_edges": added,
            "num_removed": len(removed),
            "num_added": len(added),
            "flow_delta": flow_delta,
        }
        print(f"  {name}: {len(removed)} edges removed, "
              f"{metrics['num_arrived']} vehicles arrived, "
              f"avg wait {metrics['avg_waiting_time']:.1f}s")

    out_path = os.path.join(out_dir, "dashboard_data.pkl")
    with open(out_path, "wb") as f:
        pickle.dump(data, f)
    print(f"\nSaved dashboard data to {out_path}")
